require 'options'
require 'treesitter'
require 'lsp'
require 'statusline'
require 'remaps'
require 'colemak'
require 'plugins'
require 'color'
require 'telescope'
-- require 'rust'
-- require'nvim-web-devicons'.get_icon(filename, extension, options)
