-- movements
vim.keymap.set('n', 'n', 'j', {noremap = true})
vim.keymap.set('n', 'e', 'k', {noremap = true})
vim.keymap.set('n', 'i', 'l', {noremap = true})
vim.keymap.set('n', 'm', 'h', {noremap = true})
vim.keymap.set('n', 's', 'i', {noremap = true})
vim.keymap.set('n', 'j', 'e', {noremap = true})
vim.keymap.set('n', 'h', 'b', {noremap = true})
vim.keymap.set('n', 'k', 'n', {noremap = true})
vim.keymap.set('n', 'K', 'N', {noremap = true})
vim.keymap.set('n', 'l', 's', {noremap = true})

vim.keymap.set('v', 'n', 'j', {noremap = true})
vim.keymap.set('v', 'e', 'k', {noremap = true})
-- vim.keymap.set('v', 'i', 'l', {noremap = true})
vim.keymap.set('v', 'm', 'h', {noremap = true})
vim.keymap.set('v', 's', 'i', {noremap = true})
vim.keymap.set('v', 'j', 'e', {noremap = true})
vim.keymap.set('v', 'h', 'b', {noremap = true})
vim.keymap.set('v', 'k', 'n', {noremap = true})
vim.keymap.set('v', 'K', 'N', {noremap = true})
vim.keymap.set('v', 'l', 's', {noremap = true})

-- escape
vim.keymap.set('i', 'ii','<Esc>')
vim.keymap.set('i', 'iI','<Esc>')
vim.keymap.set('i', 'iI','<Esc>')
vim.keymap.set('i', 'Ii','<Esc>')
vim.keymap.set('t', 'i','<C-\\><C-n>')
vim.keymap.set('t', 'I','<C-\\><C-n>')
vim.keymap.set('t', 'i','<C-\\><C-n>')
vim.keymap.set('t', 'I','<C-\\><C-n>')

vim.keymap.set('n', 's', 'i')
vim.keymap.set('n', 'S', 'I')
vim.keymap.set('v', 'S', 'I')
